# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 439ae5fc646096e1259ff8e6464e787b5debae29082234681f360d9d96a62e7e65fc7c227af55d47d5ae0fce9f5913fdae9f5e6b1b8e11100ce62866b5bf98fd

test:
  secret_key_base: 1f4e2bcd0aa6af8b03607eddf488c464e2370b2a304f5a40da6bb6b44ad8e21536fb6ac1553e7e6e8c6f9edb50f24c76257f950b0a96671e592b14ff90c4a9aa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
